jenkins_agent:
    build: .
    dockerfile: Dockerfile_opensdl_new
    restart: always
    labels:
      container_group: jenkins

jenkins_agent_open_sdl:
    build: .
    dockerfile: Dockerfile_opensdl
    restart: always
atf_slave:
    build: .
    dockerfile: Dockerfile_opensdl
    labels:
      container_group: jenkins
jenkins_agent_atf_14:
    build: .
    dockerfile: Dockerfile_jenkins_agent_atf_14
jenkins:
    image: jenkinsci/jenkins:latest
    container_name: jenkins_server
    environment:
     - JENKINS_JAVA_OPTIONS=-Dmail.smtp.starttls.enable=true
     - JENKINS_OPTS=-Dmail.smtp.starttls.enable=true
     - JAVA_ARGS=-Dmail.smtp.starttls.enable=true
     - JENKINS_OPTS=mail.smtp.starttls.enable=true
     - JAVA_OPTS=-Dmail.smtp.starttls.enable=true -Djava.awt.headless=true
    links:
     - jenkins_agent:jenkins
    ports:
     - "8080:8080"
     - "50000:50000"
     - "23:22"
    volumes:
     - "/home/jenkins/docker/jenkins_files:/var/jenkins_home"
     - "/home/jenkins/jenkins_temp:/var/tmp"
    restart: always
    labels:
      container_group: jenkins

artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
     - "8081:8081"
    volumes:
     - "/home/jenkins/docker/art/artifactory_data:/var/opt/jfrog/artifactory/data"
     - "/home/jenkins/docker/art/artifactory_logs:/var/opt/jfrog/artifactory/logs"
     - "/home/jenkins/docker/art/artifactory_etc:/var/opt/jfrog/artifactory/etc"
    restart: always
    labels:
      container_group: jenkins

elastic:
    image: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"

kibana:
    image: kibana
    environment:
     - ELASTICSEARCH_URL=http://172.17.0.9:9200
    ports:
     - "5601:5601"

dockerui:
    image: uifd/ui-for-docker
    container_name: dockerui
    ports:
     - "9000:9000"
    labels:
      container_group: jenkins